<html>
  <head>

    <style>
      .card-login {
        padding: 30px 0 0 0;
        width: 350px;
        margin: 0 auto;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="/">
					<img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
					Controle de Despesas
				</a>
				
			</div>
		</nav>

    <div class="container">    
      <div class="row">

        <div class="card-login">
          <div class="card">
            <div class="card-header">
              Login
            </div>
            <div class="card-body">
              <form method="post" action="/autenticar">
                <div class="form-group">
                  <input name="email" type="email" class="form-control" placeholder="E-mail">
                </div>
                <div class="form-group">
                  <input name="senha" type="password" class="form-control" placeholder="Senha">
                </div>
                <button class="btn btn-lg btn-info btn-block" type="submit">Entrar</button>
                
                <?php if($this->view->login == 'erro'){ ?>
                <span class="text text-danger">E-mail ou senha inválidos!!</span>
                <?php } ?>
              </form>
              
              <a href="/inscreverse" class="btn btn-lg btn-info btn-block" type="submit">Registrar-se</a>
              
             
            </div>
          </div>
        </div>
    </div>
      </div>
  </body>
</html>