<nav class="navbar navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="/">
					<img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
					Controle de Despesas
				</a>
				
			</div>
		</nav>
 <div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="img/logo.png" width="30" height="30"/>
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome']?>" class="form-control" placeholder="Nome" name="nome" minlength=5 required>
              </div>
              
              <div class="form-group">
                <input type="email" value="<?= $this->view->usuario['email']?>" class="form-control" placeholder="E-mail" name="email" required>
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha']?>" class="form-control" placeholder="Senha" name="senha" minlength=6 required>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade.
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Registrar-se</button>
              
               <?php
                if($this->view->erroCadastro){?>
                  <small class="form-text text-danger">Erro ao tentar realizar o cadastro, verifique os campos digitados</small>
                  <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

